 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "hello from Build section"
       - run: sleep 25
   deploy:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "hello from Deploy section"
       - run: sleep 15
       
 workflows:
   version: 2
   build_and_deploy:
     jobs:
       - build
       - deploy
